# Generated by Django 5.2.18 on 2026-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='content',
            new_name='text',
        ),
    ]
