# Generated by Django 5.2.18 on 2026-10-07 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_content_unit_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicunit',
            options={'ordering': ['position', '-added_at']},
        ),
        migrations.AddField(
            model_name='topicunit',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='state',
            field=models.CharField(choices=[('learning', 'Learning'), ('learned', 'Learned')], default='learning', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('user', 'text')},
        ),
    ]
